### ISSUE TITLE
It can not delete k/v recursively

### ISSUE THREAD

**Issue by Wang-Kai** [evildecay/etcdkeeper#10]
`/name` & `/server` not delete successfully

<img width="823" alt="2018-05-31 11 01 47" src="https://user-images.githubusercontent.com/13144386/40758932-46194ea0-64c2-11e8-9c44-c289b1129ba1.png">
<img width="408" alt="2018-05-31 11 04 20" src="https://user-images.githubusercontent.com/13144386/40758944-55bf8c7a-64c2-11e8-9bab-5de75020c200.png">

**Comment by evildecay** [comment]
@Wang-Kai Cannot delete root directory. Right-click on the node you want to delete, except the root node. The root directory is selected in your example.
