### ISSUE TITLE
unzip can't open etcdkeeper-v0.7.8-linux_arm64.zip

### ISSUE THREAD

**Issue by lcsin** [evildecay/etcdkeeper#101]
Archive:  etcdkeeper-v0.7.8-linux_arm64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of etcdkeeper-v0.7.8-linux_arm64.zip or
        etcdkeeper-v0.7.8-linux_arm64.zip.zip, and cannot find etcdkeeper-v0.7.8-linux_arm64.zip.ZIP, period.

**Comment by evildecay** [comment]
Merge the same issue into #99
