### ISSUE TITLE
merge your version switcher

### ISSUE THREAD

**Issue by Raboo** [evildecay/etcdkeeper#11]
@AndresCidoncha created a nice version switcher in his fork.
It's much more intuitive than having to go to the correct URL.

@AndresCidoncha perhaps you could create a pull request from your fork?
Forking a project and keeping general improvements for your self is not the best way to improve a project.

Thanks

**Comment by AndresCidoncha** [comment]
@Raboo I'm going to do right now.
I totally forgot about do the PR, sorry about that.

**Comment by Raboo** [comment]
@AndresCidoncha Thanks!

**Comment by Raboo** [comment]
lets hope @evildecay have time to merge it, I'll close this issue now.
