### ISSUE TITLE
Any plan to support etcd cluster?

### ISSUE THREAD

**Issue by cncal** [evildecay/etcdkeeper#16]
Etcdkeeper makes it very convenient to manage etcd single member. 👍 But now I use etcd cluster intended for HA. **So etcdkeeper has any enhancement plan to support etcd cluster?**

**Comment by Raboo** [comment]
I'm using it with a cluster.
Perhaps you can describe in more details the issues you are having with etcdkeeper and your etcd cluster?

**Comment by cncal** [comment]
@Raboo Do you make it by opening several etcdkeepers  with different-value tag `-h`?

**Comment by Raboo** [comment]
Well I connect to one node.
You only need to connect to one of your nodes, the keys you read and write are from the entire cluster.
If you have a service discovery address or a DNS pointing at all your etcd nodes, you could use that.

**Comment by cncal** [comment]
ok, I get what you meaning.Thanks a lot!

**Comment by Hejianxiong** [comment]
> Well I connect to one node.
> You only need to connect to one of your nodes, the keys you read and write are from the entire cluster.
> If you have a service discovery address or a DNS pointing at all your etcd nodes, you could use that.

Excuse me , My etcd cluster use https ,how can etcdkeeper connect it ? On the web ,I write https://ip:2379 ,it does`t work

**Comment by evildecay** [comment]
@Hejianxiong 

Set flags when start etcdkeeper and make sure that etcd has tls enabled.
```
  -usetls
        use tls (only v3)
  -cacert string
        verify certificates of TLS-enabled secure servers using this CA bundle (only v3)
  -cert string
        identify secure client using this TLS certificate file (only v3)
```
