### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by thehappycoder** [evildecay/etcdkeeper#17]
Ran the mac version:
$ /Applications/etcdkeeper/etcdkeeper
2019/04/09 07:20:14 listening on 0.0.0.0:8080

Then opened `http://127.0.0.1:8080/etcdkeeper` in browser.

**Comment by evildecay** [comment]
If open `http://127.0.0.1:8080` what will you see?

**Comment by thehappycoder** [comment]
Same problem

**Comment by Ivru** [comment]
Same problem on linux_x86_64
```
$ /opt/etcdkeeper/etcdkeeper &
[1] 10621
2019/04/12 10:18:10 listening on 0.0.0.0:8080
$ curl 127.0.0.1:8080
404 page not found
$ curl 127.0.0.1:8080/etcdkeeper
404 page not found

```

**Comment by evildecay** [comment]
@Ivru @thehappycoder 
I found the cause of the problem, there is a problem with the read path。
Temporary solution: 
```shell
cd <your path>/etcdkeeper
./etcdkeeper
```

**Comment by evildecay** [comment]
The [v0.7.4](https://github.com/evildecay/etcdkeeper/releases/tag/v0.7.4) version has fixed the bug.
Thank you for your report.
