### ISSUE TITLE
run in docker container v3 api with tls not working 

### ISSUE THREAD

**Issue by liurongwei** [evildecay/etcdkeeper#18]
run in docker container v3 api with tls not working , but run it out of container only in the host will work properly .

![微信图片_20190424193424](https://user-images.githubusercontent.com/1342352/56656476-35959a80-66c8-11e9-9787-44dfd6d7e403.png)

**Comment by evildecay** [comment]
Actually I didn't use it in docker, the docker configuration was contributed by others. If there is a problem with docker, I hope someone can help me fix it.

**Comment by Raboo** [comment]
I run it in docker, but not a TLS setup.
@liurongwei is there any logs? What does the statusText say? Timeout?
Provide as much details as possible.

So etcdkeeper tries to connect to a TLS etcd cluster?

**Comment by w38351479** [comment]
一样遇到该问题，暂时不知道怎么解决，并且尝试自己重新用官方提供的Dockerfile构建镜像，但是失败了

**Comment by w38351479** [comment]
准确来讲，通过在里面开多一个进程是可以正常使用的“./etcdkeeper.bin -h 0.0.0.0 -p 8081 -usetls -cacert /etc/kubernetes/pki/etcd/ca.crt  -cert /etc/kubernetes/pki/etcd/server.crt  -key /etc/kubernetes/pki/etcd/server.
key” 但是不知道官方镜像如何配置使用TLS，而不是我这样开多一个进程临时解决问题

**Comment by w38351479** [comment]
因为打包失败，最后使用上面提供的etcdkeeper-v0.7.5-linux_x86_64.zip算了，反正镜像并不是最新的0.7.5，而是0.7.2，估计是打包失败才没更新吧

**Comment by evildecay** [comment]
The Dockerfile has been updated and the official image has been released (https://hub.docker.com/r/evildecay/etcdkeeper). The tls configuration is not included in the official image, I want to have time to improve the configuration of tls. If you want to use tls in docker, add the tls configuration to the Dockerfile to create the image. If you have any questions, please feel free to give feedback, thank you!
