### ISSUE TITLE
Error token with auth

### ISSUE THREAD

**Issue by chris93111** [evildecay/etcdkeeper#19]
Hello

they are error when i refresh etcdkeeper 

![Capture1](https://user-images.githubusercontent.com/27526373/57240037-e176a880-702d-11e9-92f3-1f03ef203a0c.PNG)

in etcd they are error token 

![Capture2](https://user-images.githubusercontent.com/27526373/57240088-fd7a4a00-702d-11e9-81b6-4168a1482d01.PNG)

need restart etcdkeeper or change target ui (switch 127.0.01 to localhost)

**Comment by evildecay** [comment]
Which etcd version v2 or v3? I tested it and found no problem. What is the specific operational process that will produce this error?

**Comment by evildecay** [comment]
This issue has been fixed and a new version has been released. [v0.7.5](https://github.com/evildecay/etcdkeeper/releases/tag/v0.7.5)
