### ISSUE TITLE
build a office docker image?

### ISSUE THREAD

**Issue by zgfh** [evildecay/etcdkeeper#21]
can we build a office docker image to easy deploy?

**Comment by evildecay** [comment]
I haven't used docker yet, docker is contributed by others, and I hope someone can help me make it if needed.

**Comment by Raboo** [comment]
@evildecay 
1. Setup a docker account.
2. Link your docker account to github https://docs.docker.com/docker-hub/builds/link-source/.
3. Create a public repository with automated build https://docs.docker.com/docker-hub/builds/.
4. Any questions or you need help setting up rules, just ask me and I'll try to guide you through it.

**Comment by evildecay** [comment]
@Raboo Thanks！I will learn about docker when I have time.

**Comment by Raboo** [comment]
Ok, I would do it for you if I could, but the problem is that Docker Hub requires admin access to the GitHub repo because it wants to setup the webhook automatically. And GitHub doesn't allow selective permissions.

**Comment by zgfh** [comment]
👍

**Comment by evildecay** [comment]
I made the image on the docker hub (https://hub.docker.com/r/evildecay/etcdkeeper), thanks to @Raboo 's help!

**Comment by zgfh** [comment]
👍,and should we update readme?
