### ISSUE TITLE
get etcd endpoint from environment variable

### ISSUE THREAD

**Issue by idoham** [evildecay/etcdkeeper#22]
Hi,
Thanks for the gr8 work
if it possible, please add the ability to set ETCD endpoint from environment variable,
currently you are using Cookies.get('etcd-endpoint');

var etcdBase = Cookies.get('etcd-endpoint');
		if(typeof(etcdBase) === 'undefined') {
			etcdBase = '127.0.0.1:2379';

**Comment by evildecay** [comment]
This is done to facilitate different users or browser clients to access different etcd services. Environment variables can only access an etcd service, it is not convenient for a client to access multiple etcd.
