### ISSUE TITLE
CPU usage is too high after running for a while

### ISSUE THREAD

**Issue by zhangjinming** [evildecay/etcdkeeper#23]
CPU usage is too high after running for a while。

top  command.
process cpu 200% .

**Comment by zhangjinming** [comment]
log :


2019/07/19 16:55:33 PUT v2 /
2019/07/19 16:55:33 http: panic serving 172.20.137.102:43145: runtime error: invalid memory address or nil pointer dereference
goroutine 5872871 [running]:
net/http.(*conn).serve.func1(0xc0037500a0)
	D:/Applications/go/src/net/http/server.go:1769 +0x139
panic(0xb18f40, 0x120e130)
	D:/Applications/go/src/runtime/panic.go:522 +0x1b5
github.com/coreos/etcd/client.(*httpKeysAPI).Set(0xc000140080, 0xd04ee0, 0xc000026088, 0x11d36cf, 0x1, 0xc00014c3c8, 0x0, 0xc0004388c0, 0x1221080, 0xc0003660e4, ...)
	D:/Develop/gocode/src/github.com/coreos/etcd/client/keys.go:353 +0x145
main.putV2(0xd03520, 0xc0004e22a0, 0xc000156b00)
	D:/Develop/projects/etcdkeeper/src/etcdkeeper/main.go:219 +0xd44
main.main.func1.1(0xd03520, 0xc0004e22a0, 0xc000156b00)
	D:/Develop/projects/etcdkeeper/src/etcdkeeper/main.go:57 +0x62
net/http.HandlerFunc.ServeHTTP(0xc0001c0920, 0xd03520, 0xc0004e22a0, 0xc000156b00)
	D:/Applications/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1221080, 0xd03520, 0xc0004e22a0, 0xc000156b00)
	D:/Applications/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00015c9c0, 0xd03520, 0xc0004e22a0, 0xc000156b00)
	D:/Applications/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0037500a0, 0xd04ea0, 0xc000254180)
	D:/Applications/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	D:/Applications/go/src/net/http/server.go:2884 +0x2f4
2019/07/19 16:55:33 PUT v2 /
2019/07/19 16:55:33 http: panic serving 172.20.137.102:43148: runtime error: invalid memory address or nil pointer dereference
goroutine 5929528 [running]:
net/http.(*conn).serve.func1(0xc000988000)
	D:/Applications/go/src/net/http/server.go:1769 +0x139
panic(0xb18f40, 0x120e130)
	D:/Applications/go/src/runtime/panic.go:522 +0x1b5
github.com/coreos/etcd/client.(*httpKeysAPI).Set(0xc00040c160, 0xd04ee0, 0xc000026088, 0x11d36cf, 0x1, 0xc0049261a8, 0x0, 0xc000438840, 0x1221080, 0xc000366104, ...)
	D:/Develop/gocode/src/github.com/coreos/etcd/client/keys.go:353 +0x145
main.putV2(0xd03520, 0xc0004e2000, 0xc000114100)
	D:/Develop/projects/etcdkeeper/src/etcdkeeper/main.go:219 +0xd44
main.main.func1.1(0xd03520, 0xc0004e2000, 0xc000114100)
	D:/Develop/projects/etcdkeeper/src/etcdkeeper/main.go:57 +0x62
net/http.HandlerFunc.ServeHTTP(0xc0001c0920, 0xd03520, 0xc0004e2000, 0xc000114100)
	D:/Applications/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0x1221080, 0xd03520, 0xc0004e2000, 0xc000114100)
	D:/Applications/go/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc00015c9c0, 0xd03520, 0xc0004e2000, 0xc000114100)
	D:/Applications/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000988000, 0xd04ea0, 0xc003772600)
	D:/Applications/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	D:/Applications/go/src/net/http/server.go:2884 +0x2f4
2019/07/19 16:55:33 PUT v2 /
2019/07/19 16:55:33 http: panic serving 172.20.137.102:43149: runtime error: invalid memory address or nil pointer dereference
goroutine 5929529 [running]:
net/http.(*conn).serve.func1(0xc000988140)
	D:/Applications/go/src/net/http/server.go:1769 +0x139
panic(0xb18f40, 0x120e130)
	D:/Applications/go/src/runtime/panic.go:522 +0x1b5
github.com/coreos/etcd/client.(*httpKeysAPI).Set(0xc00030a040, 0xd04ee0, 0xc000026088, 0x11d36cf, 0x1, 0xc003b78228, 0x0, 0xc003772980, 0x1221080, 0xc0003682e4, ...)
	D:/Develop/gocode/src/github.com/coreos/etcd/client/keys.go:353 +0x145
main.putV2(0xd03520, 0xc0002ca460, 0xc000156a00)
	D:/Develop/projects/etcdkeeper/src/etcdkeeper/main.go:219 +0xd44
main.main.func1.1(0xd03520, 0xc0002ca460, 0xc000156a00)
	D:/Develop/projects/etcdkeeper/src/etcdkeeper/main.go:57 +0x62
net/http.HandlerFunc.ServeHTTP(0xc0001c0920, 0xd03520, 0xc0002ca460, 0xc000156a00)
	D:/Applications/go/src/net/http/server.go:1995 +0x44

**Comment by evildecay** [comment]
How do you operate, which will lead to high CPU usage? Also, why do you have the 'PUT /' operation in the v2 version?

**Comment by zhangjinming** [comment]
Normal use of ectdkeeper configuration etcd, will appear for a long time (2-3 days). The request is etcdkeeper web, version is v2 .

**Comment by zhangjinming** [comment]
> How do you operate, which will lead to high CPU usage? Also, why do you have the 'PUT /' operation in the v2 version?

Is it a bug in the v2 version? should be GET v2 /  ?

**Comment by evildecay** [comment]
@zhangjinming V2版本更不应该出现PUT / 这个操作，因为V2的根目录就是 / 。如果时这个设置导致的，那确实是个BUG。
