### ISSUE TITLE
Etcdkeeper always timeout when saving a file (Run with -h -p) 

### ISSUE THREAD

**Issue by ezhishui** [evildecay/etcdkeeper#25]
Etcdkeeper works well at local startup, but if you save a value with the - H - P parameter, timeout occurs, and HTTP put requests are sent only after timeout occurs. Specific phenomena can be seen in this link operation video.

http://download.voicecloud.cn/opps/20190828154845/VID_20190828_153704.mp4

**Comment by ezhishui** [comment]
额 不知道怎么了又不复现了，可以正常使用了。不好意思。

**Comment by evildecay** [comment]
OK，我还没来的及测试问题。如果有问题再讨论吧。
