### ISSUE TITLE
how to use etcdkeeper after enable etcd auth

### ISSUE THREAD

**Issue by OPWD** [evildecay/etcdkeeper#27]
as title. 
after i enable the authentication of etcd and revoke the role guest.
Role: guest
KV Read:
KV Write:
etcd keeper report an erroe :
110: The request requires user authentication (Insufficient credentials) [0]

**Comment by evildecay** [comment]
The first step, if you are logging in for the first time, log in as the root user first, so that the root user can obtain the permissions of other users. After opening the page, you don't need to log in as root.
In the second step, switch to the user you want to use to log in to the display.
