### ISSUE TITLE
add versioned tags to offical docker image

### ISSUE THREAD

**Issue by Raboo** [evildecay/etcdkeeper#28]
Hi,

@evildecay I suggest you add versioned tags to the docker image so people can choose what version to download.

You can set it up by adding the following rule in automated builds:

| Docker Tag | Source |
| :--: |:--:|
| {sourceref} |/^v([0-9.]+)$/ |

Like this:
![Screenshot 2019-09-12 at 14 57 14](https://user-images.githubusercontent.com/1148206/64786322-7b1b0d00-d56e-11e9-89c1-0a2856804050.png)

Next time you add push a new git version tag, it will create a image with that version.

**Comment by evildecay** [comment]
OK, tag rules have been added, thanks for the help!

**Comment by Raboo** [comment]
Cool, thanks!
