### ISSUE TITLE
404 for http://localhost:8080/etcdkeeper

### ISSUE THREAD

**Issue by yudar1024** [evildecay/etcdkeeper#29]
start command
```
 ./etcdkeeper -cacert /etc/kubernetes/pki/etcd/ca.crt -key /etc/kubernetes/pki/etcd/healthcheck-client.key -cert /etc/kubernetes/pki/etcd/healthcheck-client.crt -p 8080 -usetls

[root@master1 etcdmanagelog]# curl http://localhost:8080/etcdkeeper
404 page not found

```
then change to default configuration to start, still not working

```
[root@master1 ~]# ./etcdkeeper
2019/09/18 17:39:09 listening on 0.0.0.0:8080
[root@master1 etcdmanagelog]# curl http://localhost:8080/etcdkeeper
404 page not found

```

**Comment by evildecay** [comment]
I did not find this problem. If -h <hostname> is accessible? Or what is the result of using a browser to access?

**Comment by yudar1024** [comment]
-h is available, broswer reponse 404, page not found
```
[root@master1 ~]# ./etcdkeeper -h
flag needs an argument: -h
Usage of ./etcdkeeper:
  -auth
        use auth
  -cacert string
        verify certificates of TLS-enabled secure servers using this CA bundle
  -cert string
        identify secure client using this TLS certificate file
  -h string
        host name or ip address (default "0.0.0.0")
  -key string
        identify secure client using this TLS key file
  -p int
        port (default 8080)
  -sep string
        separator (default "/")
  -usetls
        use tls
```

**Comment by Raboo** [comment]
@yudar1024 "https" when using -usetls

**Comment by gtato** [comment]
I am pretty much having all the errors reported here. 
When I run the dockerized one, the browser hangs.
When I run it on my laptop directly, I get a 404.

**Comment by sfxworks** [comment]
Same results as above. 

I am port-forwarding my etcd server from k8s, but it's bound to localhost:2379. 

```
docker run -p 8080 evildecay/etcdkeeper:v0.7.6
Unable to find image 'evildecay/etcdkeeper:v0.7.6' locally
v0.7.6: Pulling from evildecay/etcdkeeper
21c83c524219: Already exists
cba3307ef371: Pull complete
83457583e5c3: Pull complete
09fc7fc12a0c: Pull complete
41b716d2e8ec: Pull complete
Digest: sha256:f70a3f393f21447c9e68c08ba53f7c6557190ec4ff1481bf74042b204af75416
Status: Downloaded newer image for evildecay/etcdkeeper:v0.7.6
2020-07-22 18:07:20.909011 I | listening on 0.0.0.0:8080
```
```
curl -I localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

**Comment by dselans** [comment]
etcdkeeper does not bundle the assets in the binary - you must start the binary from the same directory that contains the `assets` dir.

@yudar1024 it looks like you're starting the app from `~` - does that dir also contain `assets`?

**Comment by nareshv** [comment]
The fix is to copy the binary `etcdkeeper` in the same folder as the `assets` folder. That worked for me.

**Comment by Eutop1a** [comment]
> The fix is to copy the binary `etcdkeeper` in the same folder as the `assets` folder. That worked for me.

Thanks a lot, I had move the etcdkeeper to another folder excepted assets folder, the browser response 404. AfterI moving assets folder to etcdkeeper folder, it works.
