### ISSUE TITLE
client request timeout (5 seconds) is  too little

### ISSUE THREAD

**Issue by Sumhua** [evildecay/etcdkeeper#35]
in some cases,request time out happended ; could make this editable?

**Comment by evildecay** [comment]
Is the connection timeout too short?

**Comment by EdHunter87** [comment]
I am seeing a timeout when I try to connect to a etcd v2 cluster. The same cluster works on v3 (which has some test data), v2 is where all the current bulk of the data lives.

Error popup:
`{"readyState":0,"status":0,"statusText":"timeout"}`

**Comment by evildecay** [comment]
Use `./etcdkeeper -timeout 10` to set the client connection timeout.

**Comment by EdHunter87** [comment]
I must be really bad at go language, I have tried a couple of times. I see it under the go/bin directory, and the new timeout option. When I run the command I can't get in the webpage to come up.

**Comment by evildecay** [comment]
@EdHunter87 v2 or v3?

**Comment by evildecay** [comment]
@EdHunter87 I know, it is ajax timeout of html. Added the timeout parameter in the latest index.html. In index.html [line 149](https://github.com/evildecay/etcdkeeper/blob/master/assets/etcdkeeper/index.html#L149), please modify the size you need.
