### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by zhupanming** [evildecay/etcdkeeper#42]
点击登录总是弹出显示 user name is empty 的窗口，这是为啥

**Comment by zhupanming** [comment]
![图片](https://user-images.githubusercontent.com/30398610/83505176-0458e200-a4f8-11ea-919d-f9055b781574.png)
用户名和密码都是正确的

**Comment by evildecay** [comment]
1. 检查etcd是否启用了auth，需要使用etcdctl命令启用。
2. 检查etcdkeeper启动参数是否设置了-auth选项。
