### ISSUE TITLE
throw timeout error

### ISSUE THREAD

**Issue by simonhou** [evildecay/etcdkeeper#47]
I met follow error when accessing ui
{"readyState":0,"status":0,"statusText":"timeout"}

**Comment by StephenLee1991** [comment]
first you can use "-timeout" tag to make the client connect to etcd time longer, second you can modify the index.html line 149 to make ajax timeout of html longer.

**Comment by evildecay** [comment]
@StephenLee1991 The answer is exactly what I want to say. Timeout should be a larger timeout if there is a lot of data.
