### ISSUE TITLE
The server needs to initialize the root user.

### ISSUE THREAD

**Issue by iamdempa** [evildecay/etcdkeeper#48]
Hi,

I am the root user and I have already created another user with separate login credentials. 

But when I use the etcd-keeper to login with the new user created, it gives the error "The server needs to initialize the root user."

I mean, if I were to give access to another user for viewing only specific set of keys in my production etcd cluster, why he needs to initialize it with root user? That is giving him the root username and password.And nobody wants that. 

How can I get rid of this warning?

**Comment by iamdempa** [comment]
Here's a screenshot of the warning i am getting when i try to use newly created user's credentials to login.

![image](https://user-images.githubusercontent.com/32482769/99034920-5a03e100-25a4-11eb-85cf-d1302b6bd71b.png)

**Comment by evildecay** [comment]
After etcd is started each time, any machine browser is required to open the page for root user login, and the root information will be recorded in the server. In this way, the root information authentication is not required when the browser of other machines is opened again.

**Comment by iamdempa** [comment]
I don't get it. Why any machine browser needs to login with the root user credentials first? So there is no point in creating another user with different credentials and importantly it is not possible to share the root credentials with other users. So, if I am the admin, I have the root access. And I have developers who needs only **limited** access. That's why I even created a new user. So as per your explanation, I need to share the root user credentials with each and every developer so they can initialize first and then log with their user credentials? @evildecay @gothrek22 @jim3ma @AndresCidoncha

**Comment by iamdempa** [comment]
Hi, can I have an update on this, please?

**Comment by evildecay** [comment]
@iamdempa What I mean is that you only need to log in as root once on one of the machines after starting or restarting etcdkeeper. Others do not need to log in as root on other machines.

**Comment by yue-zz-le** [comment]
I use read-only user login, but it can write?
