### ISSUE TITLE
etcdserver: user name is empty

### ISSUE THREAD

**Issue by anchen418857063** [evildecay/etcdkeeper#51]
etcdserver: user name is empty

输入正确的用户密码后一直弹出 这个错误，我搭建的 etcd集群是etcd-v3.4.14 版本

**Comment by evildecay** [comment]
etcdkeeper启动得时候设置了-auth参数了吗？

**Comment by fananchong** [comment]
我执行：
```shell
export ETCDCTL_API=3
etcdctl --endpoints="http://172.26.150.125:12379,http://172.26.150.125:22379,http://172.26.150.125:32379" user add root
etcdctl --endpoints="http://172.26.150.125:12379,http://172.26.150.125:22379,http://172.26.150.125:32379" auth enable
```
然后，etcdkeeper 界面输入 root 123456 密码后，提示 etcdserver: user name is empty

**Comment by evildecay** [comment]
@fananchong 启动etcdkeeper后第一次打开etcdkeeper首页自动弹出输入用户名密码了吗？

**Comment by fananchong** [comment]
> @fananchong 启动etcdkeeper后第一次打开etcdkeeper首页自动弹出输入用户名密码了吗？

无

**Comment by evildecay** [comment]
启动命令--auth=true没有起作用，你改成
```docker run --name=etcdkeeper -d --restart=always -p 8080:8080 evildecay/etcdkeeper -auth```
试试

**Comment by evildecay** [comment]
> > @fananchong 启动etcdkeeper后第一次打开etcdkeeper首页自动弹出输入用户名密码了吗？
> 
> 无

改成
```docker run --name=etcdkeeper -d --restart=always -p 8080:8080 evildecay/etcdkeeper --auth=true```
试试

**Comment by fananchong** [comment]
> > > @fananchong 启动etcdkeeper后第一次打开etcdkeeper首页自动弹出输入用户名密码了吗？
> > 
> > 
> > 无
> 
> --auth=true似乎没有生效，改成
> `docker run --name=etcdkeeper -d --restart=always -p 8080:8080 evildecay/etcdkeeper -auth`
> 试试

一样，提示 `etcdserver: user name is empty`

**Comment by fananchong** [comment]
发现裸开 etcdkeeper 验证功能正常：
```shell
./etcdkeeper  -auth
```
容器中不行

**Comment by evildecay** [comment]
问题如果已解决了我就关闭了。
