### ISSUE TITLE
查看键值对时，很多值都是乱码

### ISSUE THREAD

**Issue by geoffrey10** [evildecay/etcdkeeper#52]
以下图片是乱码示例
![乱码02](https://user-images.githubusercontent.com/39729960/109486263-9a3c9000-7abd-11eb-80b6-57b1d6db8487.png)
![乱码03](https://user-images.githubusercontent.com/39729960/109486265-9b6dbd00-7abd-11eb-8621-64c3c228fb5c.png)
![乱码01](https://user-images.githubusercontent.com/39729960/109486266-9c065380-7abd-11eb-92c6-5d93da353893.png)

**Comment by evildecay** [comment]
golang默认时utf8编码。你的值应该不是utf8的

**Comment by buffge** [comment]
那是pb格式 二进制的

**Comment by haobiaosheng** [comment]
请问这个问题怎么解决？

**Comment by evildecay** [comment]
@haobiaosheng 请确认你的数据的编码，默认是utf8编码，非utf8的编码暂时没法切换。
