### ISSUE TITLE
how to set etcdkeeper with anither server with etcd?

### ISSUE THREAD

**Issue by vincentwc** [evildecay/etcdkeeper#53]
I deployment etcdkeeper in server which is different with etcd and can't  access，but it's useful when i deployment etcdkeeper  in serer whcih is same with etcd, why? Hope your help

**Comment by evildecay** [comment]
Etcd and Etcdkeeper are deployed on different machines, can Etcdkeeper not access Etcd? Is there a screenshot?

**Comment by vincentwc** [comment]
> Etcd and Etcdkeeper are deployed on different machin
<img width="757" alt="etcdkeeper" src="https://user-images.githubusercontent.com/31959888/118606883-8403bd80-b7ea-11eb-875e-7db4bcd59244.png">
es, can Etcdkeeper not access Etcd? Is there a [screenshot?](url)

it's just like this,   My bootstrap command line is `etcdkeeper.exe -h 127.0.0.1 -p 8000`

**Comment by evildecay** [comment]
The error seems to be that the connection has timed out. I don't know if there are any security restrictions on the Etcd machine?

**Comment by vincentwc** [comment]
> The error seems to be that the connection has timed out. I don't know if there are any security restrictions on the Etcd machine?

You mean it's just machine security restrictions?  ok, i'll check it  again, thinks
