### ISSUE TITLE
etcd cluster应该如何连接？

### ISSUE THREAD

**Issue by mymeatball** [evildecay/etcdkeeper#56]
安装了etcd keeper。访问端口后默认连接127.0.0.1:2379.
这个默认连接可以修改吗？需要在哪里指定？
集群模式修改的格式是什么，我是3个节点的集群，把三个节点ip:2379都写进去吗？

**Comment by evildecay** [comment]
可以修改，鼠标单击一下地址，直接在这个输入框里改就行了，不用都写，写一个即可。

**Comment by mymeatball** [comment]
![image](https://user-images.githubusercontent.com/51807672/124426535-c1250e80-dd9c-11eb-87eb-564758a8759b.png)
是这里吗？ 我鼠标点好像没效果。难道是浏览器的问题。。

**Comment by mymeatball** [comment]
感谢。原来直接删除127.0.0.1就可以。我一直以为要点击哪里然后会出来哥弹窗。
