### ISSUE TITLE
为何开启了鉴权auth enable。总是报错“etcdserver: user name is empty”

### ISSUE THREAD

**Issue by mymeatball** [evildecay/etcdkeeper#57]
输入命令auth enable后，如下报错“etcdserver: user name is empty”：
![image](https://user-images.githubusercontent.com/51807672/124479556-fcddc980-ddd8-11eb-8980-3c1da36a1ca6.png)
![image](https://user-images.githubusercontent.com/51807672/124479612-06673180-ddd9-11eb-9bed-123fa3a9c05a.png)
用户root 密码etcd
![image](https://user-images.githubusercontent.com/51807672/124479709-1da61f00-ddd9-11eb-804b-4585142af426.png)

然后使用root etcd去关闭鉴权后，访问正常，如下：
![image](https://user-images.githubusercontent.com/51807672/124479800-357da300-ddd9-11eb-8b65-3f574389b531.png)
清空用户名密码后
![image](https://user-images.githubusercontent.com/51807672/124479873-45958280-ddd9-11eb-8070-67be0338ec1e.png)
访问正常如下：
![image](https://user-images.githubusercontent.com/51807672/124479917-50e8ae00-ddd9-11eb-85d7-9850ad5be5df.png)

**Comment by mymeatball** [comment]
这种问题常见吗？可否提供一些帮助。
要是不常见问题的话，我再自己看看。

**Comment by evildecay** [comment]
确保使用etcdctl创建了root用户。然后使用etcdctl开启etcd的权限。再启动etcdkeeper时加上 -auth参数。这样第一次打开etcdkeeper的页面时会提示你输入一次etcd的root用户密码。以后再打开可以用其他用户登录了。

**Comment by mymeatball** [comment]
感谢！解决了。
我应该先仔细读读文档的~
