### ISSUE TITLE
Authentication support? (etcd)

### ISSUE THREAD

**Issue by kapolos** [evildecay/etcdkeeper#6]
Is this a planned feature?

**Comment by evildecay** [comment]
Hi @kapolos 
As the work is relatively busy, there is no time to add permission features. I can simply support the username and password settings on the server side. (Of course, you can also compile your own server source to add)

**Comment by kapolos** [comment]
Hi @evildecay ! Thank you, adding the username/password on the server side would be awesome! 👍 🍺 

Imho, that is all that's needed because for the front-end, one can put it behind a reverse proxy (like Caddy) and secure it like that.

**Comment by evildecay** [comment]
@wonderivan I hope to have time to add this feature during the Spring Festival. If someone can contribute to help me, I am also very welcome.

**Comment by evildecay** [comment]
Support to get data based on etcd user permissions.[v0.7.3](https://github.com/evildecay/etcdkeeper/releases)
