### ISSUE TITLE
How to install the etcdkeeper in the MacOS?

### ISSUE THREAD

**Issue by ZonzeeLi** [evildecay/etcdkeeper#61]
I don't see the executable file. 'etcdkeeper' is the document file.

**Comment by evildecay** [comment]
You can directly download the version of the macos platform? [Release download](https://github.com/evildecay/etcdkeeper/releases)

**Comment by ZonzeeLi** [comment]
I have downloaded darwin.zip. So how should Mac OS configure etcdkeeper without executable file ？

**Comment by evildecay** [comment]
解压zip文件，打开一个终端，CD到解压的这个目录，执行./etcdkeeper
