### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by QiuToo** [evildecay/etcdkeeper#62]
[root@master01 ~]# vim  /lib/systemd/system/etcdkeeper.servic
[Unit]
Description=etcdkeeper service
After=network.target
[Service]
Type=simple
ExecStart=/usr/local/bin/etcdkeeper  -p 8800  -h  192.168.2.66
ExecReload=/bin/kill -HUP
KillMode=process
Restart=on-failure
PrivateTmp=true
[Install]
WantedBy=multi-user.target

 [root@master01 ~]# systemctl status etcdkeeper.service 
● etcdkeeper.service - etcdkeeper service
   Loaded: loaded (/usr/lib/systemd/system/etcdkeeper.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2022-01-12 12:15:23 CST; 5s ago
 Main PID: 9740 (etcdkeeper)
    Tasks: 4
   Memory: 4.5M
   CGroup: /system.slice/etcdkeeper.service
           └─9740 /usr/local/bin/etcdkeeper -p 8800 -h 192.168.2.66

1月 12 12:15:23 master01 systemd[1]: Started etcdkeeper service.
1月 12 12:15:23 master01 systemd[1]: Starting etcdkeeper service...
1月 12 12:15:23 master01 etcdkeeper[9740]: listening on 192.168.2.66:8800
[root@master01 ~]# curl 192.168.2.66:8800
404 page not found
root@master01 ~]# ls  -l  /usr/local/bin/etcdkeeper 
-rwxr-xr-x 1 root root 19755714 6月   8 2020 /usr/local/bin/etcdkeeper
What's the reason？

**Comment by evildecay** [comment]
Access address:
```bash
curl http://192.168.2.66:8800/etcdkeeper
```

**Comment by cyb0225** [comment]
Hi @QiuToo,  I have encountered the same error, and I found this artical which successfully solve my problem.
https://lightrun.com/answers/evildecay-etcdkeeper-404-for-httplocalhost8080etcdkeeper
In short,  you must start the binary from the same directory that contains the assets dir.

**Comment by evildecay** [comment]
Same issue, merged into [#29](https://github.com/evildecay/etcdkeeper/issues/29)
