### ISSUE TITLE
view information from the page error send message larger than max

### ISSUE THREAD

**Issue by bestcx** [evildecay/etcdkeeper#63]
etcdkeeper has already started successfully. 
However,  the following error occurs when I try to view information from the page
rpc error: code = ResourceExhausted desc = trying to send message larger than max (6161420 vs. 2097152)
The MaxCallSendMsgSize parameter defaults to 2M, I think we should expose this parameter

**Comment by evildecay** [comment]
@bestcx Thanks for your contribution.
