### ISSUE TITLE
打开页面报错

### ISSUE THREAD

**Issue by LyonNee** [evildecay/etcdkeeper#65]
通过docker-compose部署 etcdkeeper，进入页面就弹出报错
![image](https://user-images.githubusercontent.com/30852031/154933522-20bb1abe-b70f-4bf9-b56a-d65d956ede8b.png)

我不知道是不是我的 docker-compose.yaml 配置的有错误，还是我启动 etcd 镜像错了

这是docker-compose.yaml内容
`version: '3'
networks:
  mall:

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.2.5
    container_name: etcd1
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
    - 2379:2379
    - 2380:2380
    networks:
    - mall

  etcd2:
    image: quay.io/coreos/etcd:v3.2.5
    container_name: etcd2
    command: etcd -name etcd2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - 2379
      - 2380
    networks:
      - mall
  
  etcd3:
    image: quay.io/coreos/etcd:v3.2.5
    container_name: etcd3
    command: etcd -name etcd3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - 2379
      - 2380
    networks:
      - mall
    
  etcdkeeper:
    image: evildecay/etcdkeeper:latest
    container_name: "etcdkeeper"
    environment:
      HOST: "0.0.0.0"
    ports:
    - 8080
    networks:
    - mall
    depends_on:
    - etcd1`

**Comment by runzhliu** [comment]
这个看起来是配置etcd证书的问题，client需要通过tls配置去连接etcd
