### ISSUE TITLE
有docker运行的说明吗？

### ISSUE THREAD

**Issue by bruse-peng** [evildecay/etcdkeeper#68]
有docker运行的说明文档吗？

**Comment by zzlgo** [comment]
# etcd不开auth
docker run -d --name etcdkeeper01 evildecay/etcdkeeper
# etcd开启auth
docker run -d --entrypoint "./etcdkeeper.bin" --name etcdkeeper01 evildecay/etcdkeeper -h 0.0.0.0 -p 8080 -auth
