### ISSUE TITLE
resource can't match service context path

### ISSUE THREAD

**Issue by lakewatcher** [evildecay/etcdkeeper#71]
资源路径和接口路径不一致，很难被服务转发。
resource can't match service context path

当我访问 /etcdkeeper/ 时，请求的资源确是：/framework/easyui/themes/metro/easyui.css
When I visited /etcdkeeper,  requested resource is: / framework/easyui/themes/metro/easyui. The path is {baseurl}/framework not  {baseurl}/etcdkeeper/framework 
 

当使用转发服务时，无法处理资源转发，示例。
if i using gateway or nginx to rewrite url , encounter the scene ，for example:

![image](https://user-images.githubusercontent.com/27823963/211452821-4f6d7d55-e18e-44b1-a122-dd1cc2fbd3c9.png)

**Comment by evildecay** [comment]
我设计之初是入口是静态资源的index.html开始访问的，最初我只想单机在命令行中启动一下就访问了，所以没有考虑其他部署例如docker和ngix这些。这个PR[#50](https://github.com/evildecay/etcdkeeper/pull/50)不知道是否解决了这个问题？

**Comment by evildecay** [comment]
我测试明白了你的意思，在最新的提交我调整了静态资源的目录和加载路径，这应该解决了你说的问题。
