### ISSUE TITLE
connect to k8s etcd , but text coding  show error format

### ISSUE THREAD

**Issue by EvilJoker** [evildecay/etcdkeeper#75]
open a file with editor。but like below
----------------------------------------------------
k8s
%
scheduling.k8s.io/v1
PriorityClass�
�
system-cluster-critical"*$bda0ea22-3881-4ba6-ab28-d1e2518dcfae28B����z�
kube-apiserverUpdatescheduling.k8s.io/v1"����2FieldsV1:;
9{"f:description":{},"f:preemptionPolicy":{},"f:value":{}}��ֹ"jUsed for system critical pods that must run in the cluster, but can be moved to another node if necessary.*PreemptLowerPriority"
--------------------------------------------------------

**Comment by evildecay** [comment]
I haven't used k8s for testing. Character set garbled characters are usually inconsistent with the character set. Because it is implemented in Go language, all codes and static files use UTF-8 encoding.
