### ISSUE TITLE
如何支持多个etcd服务

### ISSUE THREAD

**Issue by oldwang12** [evildecay/etcdkeeper#79]

**Comment by tzfun** [comment]
[etcd-workbench](https://github.com/tzfun/etcd-workbench)支持

**Comment by evildecay** [comment]
支持多个ETCD服务指的是什么，访问不同的ETCD集群吗？如果是想访问不同的ETCD集群，在界面中的ETCD的服务地址这里可以输入不同的集群的机器的地址，例如 192.168.0.10:2379来访问不同的ETCD集群。
