### ISSUE TITLE
unexpected status code 404

### ISSUE THREAD

**Issue by dengzhaoexp** [evildecay/etcdkeeper#80]
I hava run etcd in a docker container and run etcdkeep in host.But i got a ploblem just like this.
![image](https://github.com/evildecay/etcdkeeper/assets/114124286/242199df-9533-4496-8130-a1850a6acfb3)

and the more information :
[root@VM-0-8-opencloudos etcdkeeper]# ./etcdkeeper -h  10.0.0.8 -p 8800
2023-06-08 22:04:02.975220 I | listening on 10.0.0.8:8800
2023-06-08 22:09:02.024672 I | POST v2 connect success.
2023-06-08 22:09:02.025938 I | unexpected status code 404

**Comment by evildecay** [comment]
I don't know much about docker, so I need to spend time to find the problem. If the problem has been solved, please tell me the solution.

**Comment by evildecay** [comment]
After testing, I found that v2 does have a problem.

**Comment by evildecay** [comment]
The test found that this is because the v2 version is not enabled by default after etcd server 3.4, and the startup option setting is required to enable the v2 version.
```
$ ./etcd --enable-v2=true
```
