### ISSUE TITLE
My key `dir_1/dir_2/name` cannot be viewed on the web page

### ISSUE THREAD

**Issue by Wang-Kai** [evildecay/etcdkeeper#9]
Maybe the keys not prefixed with `/` can not be showed on the web page .

**Comment by evildecay** [comment]
@Wang-Kai If you are not a directory, you need to set the separator parameters '-sep' when httpserver starts.

**Comment by Wang-Kai** [comment]
Maybe you were not understand my point, it is not a issue about separator .

eg: key ==> dirA/dirB/dirC/name, value ==> foo

It can be showed on the keys tree on web page .

**Comment by evildecay** [comment]
@Wang-Kai Key must start with '/', root path must be '/'

![_20180531141546](https://user-images.githubusercontent.com/6789367/40764909-2ed77c06-64dd-11e8-89e8-4eeda4fdb6d7.png)
