### ISSUE TITLE
Docker file issue due to env variable

### ISSUE THREAD

**Issue by channel960608** [evildecay/etcdkeeper#97]
When I clone the project and try to build and run the docker image, i got this issue:
```
# docker run -it --rm etcdkeeper:dev
invalid value "$PORT" for flag -p: parse error
Usage of ./etcdkeeper.bin:
  -auth
        use auth
  -cacert string
        verify certificates of TLS-enabled secure servers using this CA bundle (v3)
  -cert string
        identify secure client using this TLS certificate file (v3)
  -h string
        host name or ip address (default "0.0.0.0")
  -key string
        identify secure client using this TLS key file (v3)
  -p int
        port (default 8080)
  -sendMsgSize int
        ETCD client max send msg size (default 2097152)
  -sep string
        separator (default "/")
  -skiptls
        skip verify tls
  -timeout int
        ETCD client connect timeout (default 5)
  -usetls
        use tls
```

It seems that the 2 variables in the Dockerfile are empty, $HOST and $PORT. The bin file can't parse the arguments correctly when it executes.
`ENTRYPOINT ["./etcdkeeper.bin", "-h", "$HOST", "-p", "$PORT"]`

Besides, since we are using ENTRYPOINT in Dockerfile, we are not able to overwrite the argumnets since we have built the docker image.

**Comment by channel960608** [comment]
https://github.com/evildecay/etcdkeeper/pull/98

**Comment by evildecay** [comment]
The Docker configuration changes were also recently submitted by other contributors. I haven't had time to test them yet. Thank you for your contribution.
