### ISSUE TITLE
linux_x86_64.zip can't be opened with unzip, it seems tar file 

### ISSUE THREAD

**Issue by jackylouying** [evildecay/etcdkeeper#99]
unzip etcdkeeper-v0.7.8-linux_x86_64.zip
Archive:  etcdkeeper-v0.7.8-linux_x86_64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of etcdkeeper-v0.7.8-linux_x86_64.zip or
        etcdkeeper-v0.7.8-linux_x86_64.zip.zip, and cannot find etcdkeeper-v0.7.8-linux_x86_64.zip.ZIP, period.

**Comment by evildecay** [comment]
I'm very sorry, I packaged it using the tar command and the suffix was not changed. I should use the tar command. Next time I will change the suffix.

**Comment by evildecay** [comment]
Has been re-released in tar.gz format.
